markdown: rdiscount
pygments: true
permalink: /:year/:month/:day/:title
encoding: utf-8
comments :
  provider : disqus
  disqus :
    short_name : miguelfrde
analytics :
  provider : google
  google : 
      tracking_id : 'UA-41047087-1'
