# Site settings
baseurl: ""
url: "http://miguelfrde.com"
css_path: "/static/css/"
js_path: "/static/js/"
img_path: "/static/img/"

# Build settings
markdown: kramdown
permalink: pretty
sass:
    style: :compressed
