# Site settings
baseurl: ""
css_path: "/static/css/"
js_path: "/static/js/"
img_path: "/static/img/"

include: [".well-known"]

# SEO
url: "http://miguelfrde.com"
title: "Miguel Flores Ruiz de Eguino (miguelfrde)"
description: Miguel's personal website
author: miguelfrde
logo: https://www.gravatar.com/avatar/ed4f3cbac5a1e5e45b2f9d8102238d33.png?s=500
google_site_verification: YHzNvH1F8_UqAbVsl2ht07zAIi13m7jHvP2NLDRCaTw
facebook:
  admins: 1348682391
twitter:
  username: miguelfrde
social:
  links:
    - https://www.linkedin.com/in/miguelfrde
    - https://github.com/miguelfrde

# Build settings
markdown: kramdown
permalink: pretty
sass:
  style: :compressed

# Plugins
plugins:
  - jekyll-seo-tag
